server:
    port: 8310
    context-path: /

spring:
    application:
    # 应用名称
      name: transfer-crawler

    # 环境 dev|test|pro
    profiles:
        active: dev

    # rabbitmq
    rabbitmq:
      host: 10.0.98.75
      port: 5672
      username: admin
      password: Rabbitmq@2018
      # 支持发布确认
      publisher-confirms: true
      # 支持发布返回
      publisher-returns: true
      listener:
        simple:
          acknowledge-mode: manual
          # 指定最小的消费者数量
          concurrency: 1
          # 指定最大的消费者数量
          max-concurrency: 1
          # 是否支持重试
          retry:
            enabled: true

    # redis
    redis:
        database: 10
        host: 10.0.98.9
        port: 6385
        password:       # 密码（默认为空）
        timeout: 15000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
    # 数据库
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            url: jdbc:mysql://10.0.98.6:3306/mustang_transfer?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
            username: root
            password: root
            driverClassName: com.mysql.jdbc.Driver
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true


info:
  app:
    name: transfer-crawler
    version: 1.0


eureka:
  client:
    serviceUrl:
      defaultZone: http://transfer:password@localhost:8000/eureka
    # 缓存清单每隔30秒跟新一次
    registry-fetch-interval-seconds: 10
  instance:
    hostname: transfer-crawler
    # 实例使用ip进行访问
    prefer-ip-address: true
    # 实例显示id
    instance-id: ${spring.application.name}:${server.port}
    # 服务续约任务调用间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 5
    # 服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 20
    #状态页面和健康指标
    statusPageUrlPath: ${server.context-path}/swagger-ui.html


# Feign 开启 Hystrix
feign:
  hystrix:
    enabled: true

pagehelper:
    helperDialect: mysql
    page-size-zero: true
    reasonable: true
    params: pageNum=start;pageSize=limit;pageSizeZero=zero;reasonable=heli;count=contsql
    row-bounds-with-count: true

# Mybatis配置
mybatis:
    mapperLocations: classpath*:com/hqjy/mustang/transfer/crawler/dao/*Dao.xml
    configuration:
        map-underscore-to-camel-case: true

# shiro 不拦截路径
shiro:
  anon:
    path:
      # spring cloud 健康检查
      - /info
      - /actuator/**
      - /doc
      - /swagger-ui.html
      - /webjars/**
      - /swagger-resources/**
      - /v2/api-docs
      - /test/**
      - /resume/**