info:
  app:
    name: mustang-quartz
    version: 1.0

server:
  port: 8220
  context-path: /

spring:
  application:
    # 应用名称
    name: mustang-quartz
  # 环境 dev|test|pro
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://transfer:password@localhost:8000/eureka
    # 缓存清单每隔30秒跟新一次
    registry-fetch-interval-seconds: 10
  instance:
    hostname: mustang-quartz
    # 实例使用ip进行访问
    prefer-ip-address: true
    # 实例显示id
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    # 服务续约任务调用间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 5
    # 服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 20
    #状态页面和健康指标
    statusPageUrlPath: ${server.context-path}/swagger-ui.html

# Feign 开启 Hystrix
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 5000

# shiro 不拦截路径
shiro:
  anon:
    path:
    # spring cloud 健康检查
    - /info
    - /actuator/**
    - /doc
    - /swagger-ui.html
    - /csrf
    - /webjars/**
    - /swagger-resources/**
    - /v2/api-docs
    - /login
    - /
