info:
  app:
    name: transfer-call
    version: 1.0

server:
  port: 8330
  context-path: /

spring:
  application:
    # 应用名称
    name: transfer-call
  # 环境 dev|test|pro
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://transfer:password@localhost:8000/eureka
    # 缓存清单每隔30秒跟新一次
    registry-fetch-interval-seconds: 10
  instance:
    hostname: transfer-call
    # 实例使用ip进行访问
    prefer-ip-address: true
    # 实例显示id
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    # 服务续约任务调用间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 5
    # 服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 20
    #状态页面和健康指标
    statusPageUrlPath: ${server.context-path}/swagger-ui.html

# Feign 开启 Hystrix
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 5000

# Mybatis配置
mybatis:
  mapperLocations: classpath*:com/hqjy/mustang/transfer/call/dao/*Dao.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  page-size-zero: true
  reasonable: true
  params: pageNum=start;pageSize=limit;pageSizeZero=zero;reasonable=heli;count=contsql
  row-bounds-with-count: true

# shiro 不拦截路径
shiro:
  anon:
    path:
    # spring cloud 健康检查
    - /info
    - /actuator/**
    - /doc
    - /swagger-ui.html
    - /csrf
    - /webjars/**
    - /swagger-resources/**
    - /v2/api-docs

# tq 参数及其接口
tq:
  # 管理员账号
  adminUin: 9828307
  # 管理员密码
  password: hq88
  # 外呼接口
  call:
    # 获取token
    getToken: http://passport.hn.tq.cn:81/pulse
    # 点击外呼
    clickCall: http://vip.hn.tq.cn/vip/workMobile/clickCall
  # 服务接口地址
  webservice:
    host: http://webservice.tq.cn
    # 获取token
    getAccessToken: ${tq.webservice.host}/webservice/getAccessToken
    # 获取通话记录
    phoneRecord: ${tq.webservice.host}/webservice/phoneRecord/list
