spring:
    redis:
        database: 3
        host: 10.0.98.9
        port: 6385
        password:       # 密码（默认为空）
        timeout: 15000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
        ws-topic-name: mustang_websocket_dev #websocket推送redis主题的名称
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            url: jdbc:mysql://10.0.98.6:3306/mustang_v2?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
            username: root
            password: root
            driverClassName: com.mysql.jdbc.Driver
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

#ActiveMQ参数配置
activemq:
    # 服务器地址；failover：自动重连机制开启
    brokerURL: failover:(tcp://172.16.2.225:61616)
    # 用户名
    userName: admin
    # 密码
    password: Hqjy@2017#@!
    # 消息队列名称 配置：一个消费者一次只取1条（默认1000条），然后一条一条确认消息
    queueName:
        allot: mustang_business_dev?consumer.prefetchSize=1  # 官网，ERP, 代理网队列名称
    # 是否开启商机消息处理,默认 false
    businessHandle:
        allot: true
    # 商机消费者个数，默认1
    consumerSize:
        allot: 1
    # 失败商机，初始发送延时 默认1000 单位ms（10 * 60 * 1000）
    initialRedeliveryDelay: 600000
    # 失败商机，重试延迟时间 默认1000
    redeliveryDelay: 600000
    # 失败商机，最大重试次数，默认6 ，设置-1为无限次重试
    maximumRedeliveries: -1

rabbitmq:
    address: 10.0.98.46:5672
    username: admin
    password: mon4498
    queueName:
      ncDeal: nc.success.reg.stu.cjym.dev

#NC接口参数
nc:
  #商机信息保存到NC
  studentFromXN: http://10.0.96.247:8899/servlet/~hq/nc.impl.hq.webservice.student.StudentFromXNServlet
  #NC新增跟进记录接口
  followUpSaveUrl: http://10.0.96.247:8899/servlet/~hq/nc.impl.hq.webservice.student.StudentRecordContactServlet
  #NC商机修改接口
  updateStuRecordOrg: http://10.0.96.247:8899/servlet/~hq/nc.impl.hq.webservice.student.UpdateStuRecordOrgServlet
  #NC根据校区获取招生老师
  getTeacherUrl: http://10.0.96.247:8899/servlet/~hq/nc.impl.hq.webservice.student.GetSchoolTeacherServlet
  # 自考销售人员
  getZKSaleManUrl: http://nc.hqbis.com/servlet/~hq/nc.impl.hq.webservice.student.GetZKSaleManServlet
  #获取省份或者校区接口
  getProvinceSchoolUrl: http://api.hqjy.com/hq-school/org/get